#!/usr/bin/env python3

from cdist_manifestation.dependencies import order_dependency, require
from cdist_manifestation.types import directory, file, link

opt_bin = directory('/opt/bin', parents=True)

with require(opt_bin):
    file('/opt/bin/test', mode=755)

    with order_dependency():
        link('/opt/bin/test1', source='/opt/bin/test', type='symbolic')
        link('/opt/bin/test2', source='/opt/bin/test1', type='symbolic')
        link('/opt/bin/test3', source='/opt/bin/test2', type='symbolic')
